// 7 大模块 → 路由清单（仅列表面板级路由；新建/编辑等详情页由点击对应按钮自然触达）
export const MODULES = {
  '工作台': {
    key: 'workspace',
    routes: [
      '/unifiedInbox/list',
      '/customerSession/list',
      '/unifiedMessage/list',
      '/messageHub/list',
      '/wecomAccount/list',
    ],
  },
  '客户中心': {
    key: 'customer',
    routes: [
      '/customer360/list',
      '/customerEvent/list',
      '/clue/list',
      '/clue/statistics',
      '/tagSegmentation/list',
      '/userSegment/list',
      '/chatChannel/list',
    ],
  },
  '智能体': {
    key: 'aiAgent',
    routes: [
      '/aiAgent/list',
      '/dialogueMemory/list',
      '/intentRecognition/list',
      '/objection/list',
      '/persona/list',
      '/sopAgent/list',
      '/scriptTemplate/list',
      '/llmRouting/list',
      '/confidence/panel',
      '/humanize/panel',
      '/feedbackLoop/panel',
      '/asset-market',
      '/asset-market/my-assets',
    ],
  },
  '触达运营': {
    key: 'reach',
    routes: [
      '/marketingFlow/list',
      '/reachPipeline/list',
      '/sms/list',
      '/sms/drafts',
      '/sms/jobs',
      '/sms/config',
      '/email',
      '/email/drafts',
      '/email/jobs',
      '/email/smtp',
      '/email/info',
      '/email/guide',
      '/tiktok',
      '/tiktok/stats',
      '/tiktok/auto-reply',
      '/douyinCard',
      '/douyin/stats',
      '/douyin/auto-reply',
      '/kuaishouCard',
      '/kuaishou/stats',
      '/kuaishou/auto-reply',
      '/xiaohongshuCard',
      '/xiaohongshu/stats',
      '/xiaohongshu/auto-reply',
      '/xianyuCard',
      '/xianyu/stats',
      '/xianyu/auto-reply',
      '/batchOperation/list',
      '/livecode',
      '/shortLink',
      '/shortLink/stats',
    ],
  },
  '知识中心': {
    key: 'knowledge',
    routes: [
      '/knowledge/management',
      '/knowledge/tokens',
      '/knowledge/playground',
      '/knowledge/chunks',
      '/knowledge/external',
      '/knowledge/openapi',
      '/knowledge/statistics',
      '/knowledge/feedbacks',
      '/knowledge/batch-import',
      '/templateMarket/list',
      '/system/rag-overview',
      '/system/rag-product-config',
      '/system/rag-product',
      '/system/rag-account',
      '/aiContent/list',
    ],
  },
  '数据分析': {
    key: 'dataAnalysis',
    routes: [
      '/aiProductivity/list',
      '/conversionFunnel/list',
      '/customerJourney/dashboard',
      '/dashboardScreen/list',
      '/customReport/list',
      '/abExperiment/list',
      '/churnPrediction/list',
    ],
  },
  '系统设置': {
    key: 'system',
    routes: [
      '/platformAccount/list',
      '/teamUser/list',
      '/teamUser/role',
      '/system/config',
      '/system/material-library',
      '/system/monitor',
      '/system/obs-config',
      '/integration/list',
      '/operationLog/list',
      '/securityAudit/list',
      '/backup/list',
      '/system/guide',
    ],
  },
}

export const ALL_ROUTES = Object.entries(MODULES).flatMap(([name, m]) =>
  m.routes.map((route) => ({ module: name, key: m.key, route }))
)
